### ISSUE TITLE
Missing "DecrZero.h"

### ISSUE THREAD

**Issue by sho3string** [MirageBD/MegaTool#1]
Hello. Tried building the Megatool but get the following error because of missing header file.

$ gcc -o megatool megatool.c cruncher.c imgconvert.c
cruncher.c:37:10: fatal error: DecrZero.h: No such file or directory
   37 | #include "DecrZero.h"
      |          ^~~~~~~~~~~~
compilation terminated.

**Comment by MirageBD** [comment]
DecrZero.h is generated by the makefile:

./converttoheader.exe DecrZero.prg DecrZeroInit.prg DecrZero.symbols DecrZeroInit.symbols DecrZero.h
